name: Build

on:
  push:
    branches:
      - 'main'

concurrency:
 group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
 cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.github_token }}

      - name: Date
        id: date
        run: echo "::set-output name=BUILD_DATE::$(date '+%Y-%m-%dT%H:%M:%S%:z')"

#      - name: Publish to ghcr.io
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          context: ./dockerx64
#          platforms: linux/amd64
#          tags: |
#            ghcr.io/${{ steps.repo-name.outputs.REPO }}:${{ inputs.branch == 'master' && 'latest' || inputs.branch }}
#            ghcr.io/${{ steps.repo-name.outputs.REPO }}:v${{ inputs.version }}
#          build-args: |
#            VERSION=2.1
#            MISSARR_VERSION=${{ inputs.version }}
#            BUILD_DATE=${{ steps.date.outputs.BUILD_DATE }}
#          cache-from: type=gha
#          cache-to: type=gha,mode=max

      - name: Publish to ghcr.io
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./dockerarm64
          platforms: linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/posterizarr:latest
          build-args: |
            VERSION=1
            BUILD_DATE=${{ steps.date.outputs.BUILD_DATE }}
          cache-from: type=gha
          cache-to: type=gha,mode=max