name: Generate changelog
# on:
  # push:
    # branches:
      # - main
  # release:
    # types: [created, edited]
  # workflow_dispatch:
jobs:
  changelog-wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        fetch-depth: '0'
    - run: git checkout HEAD^
        
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        ACCESS_TOKEN: ${{secrets.CR_PAT}}
        PATH: './changelog.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements'
