name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          owner: fscorrupt
          base: main
          head: main
          merge_method: merge
          pr_title: Fork Sync
          auto_approve: true
          auto_merge: true
