# on:
  # release:
    # types: [created, edited]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "2105893"
          username: "Release Changelog"
          avatar_url: "https://github.com/fscorrupt/Posterizarr/raw/main/images/webhook.png"
          content: "||@Announcements||"
          footer_title: "Changelog"
          footer_icon_url: "https://github.com/fscorrupt/Posterizarr/raw/main/images/webhook.png"
          footer_timestamp: true
